<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputPath>..\build-output\addons\counterstrikesharp\plugins\RetakesPlugin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CounterStrikeSharp.API" Version="1.0.371" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.12" />
    <ProjectReference Include="..\RetakesPluginShared\RetakesPluginShared.csproj"><Private>false</Private></ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="lang\**\*.*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(CopyPath)' != '' ">
    <Exec Command="copy &quot;$(TargetPath)&quot; &quot;$(CopyPath)&quot; " />
    <Exec Command="copy &quot;$(TargetDir)$(TargetName).pdb&quot; &quot;$(CopyPath)&quot; " />
  </Target>
</Project>