name: Format check on pull request

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: .NET Format
        uses: zyactions/dotnet-format@v1
        with:
          workspace: test
          implicit-restore: true
