name: Check the format of .cs files

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.cs'
      - '**.csproj'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: .NET Format (RetakesPlugin)
        uses: zyactions/dotnet-format@v1
        with:
          workspace: RetakesPlugin
          implicit-restore: true

      - name: .NET Format (RetakesPluginShared)
        uses: zyactions/dotnet-format@v1
        with:
          workspace: RetakesPluginShared
          implicit-restore: true
          
